### ISSUE TITLE
A Derma Menu/GUI

### ISSUE THREAD

**Issue by iisworm** [C0nw0nk/Garrys-Mod-Anti-Cheat#5]
A menu would be cool for editing values and/or punishments. Not sure if that's in development or not yet.

**Comment by C0nw0nk** [comment]
It is not but the reason I have not done anything like that is because a derma menu needs to be restricted access to admins only what means specifying each admin addon and adding permissions for each in the code, "ulx etc" Not everyone uses the same administration addons. So if I ever do it I don't see myself doing that anytime soon but people are welcome to fork this repo and do it themselves if it is good I will merge it with the main branch.
