### ISSUE TITLE
The anti-cvar-manipulation.lua dosent seem to work at all?

### ISSUE THREAD

**Issue by jullegulle2000** [C0nw0nk/Garrys-Mod-Anti-Cheat#7]
Hello! The cvar manipulation detector dosent seem to work at all. Could you check if its outdated or update it? Thanks!

**Comment by C0nw0nk** [comment]
Maybe things have changed since I did this, Have you tried as a replacement instead of using my anti-cvar a even better alternative for detecting and preventing is cake anti-cheat.

It does not do anti-speedhack or bhop, recoil, etc like mine does since my scripts force those in at a server level, But it can still detect them and boot / ban them of the server.

https://www.gmodstore.com/scripts/view/460

You can keep the other scripts in place since I remember with cake I have seen people bhop and speedhacking still but my scripts will prevent that, Keep in mind I do not play Gmod anymore and I did make this a long time ago I see no reason why the other scripts would ever stop working but the anti-cvar i believe is because the client is spoofing and telling the server they have not modified it when they really have, Something that cake can definitely solve for you.

**Comment by jullegulle2000** [comment]
Yeah i manage to do some testing with it. Forcing the cvars on my client dosent set the "in-game" cvar to the value. It will still display 0 or whatever the server has set it to but running clientsided scripts work. Its sad that they changed it to that way. And yes, In my opinion Cake Anti-Cheat beats everything indeed. Thanks for your reply and have a wounderfull holiday:)
